### ISSUE TITLE
Allow to navigate back in hover

### ISSUE THREAD

**Issue by cristianvasquez** [nothingislost/obsidian-hover-editor#120]
First of all, thanks for the wonderful plugin!

Feature request: to allow 'Navigate Back' when inside a hover

**Comment by pjeby** [comment]
You need the Pane Relief plugin to do this; Obsidian's built-in history mechanism cannot handle separate history per pane.  Installing and enabling Pane Relief will give you history for each pane in your workspace, including hover popovers, and the history is kept even if you switch workspaces (each will have its own) or restart Obsidian.

(Note: on MacOS, the *menu* items for Navigate Forward and Navigate Back do not work correctly with Pane Relief at this time, but mouse forward/back, the arrows in the titlebar, and keyboard navigation commands all do work.  This is an issue that has to be fixed in the Obsidian app, no word yet on what release the fix will appear in.)
