### ISSUE TITLE
Incompatibility with plugin "maximise active pane"

### ISSUE THREAD

**Issue by lethefrost** [nothingislost/obsidian-hover-editor#134]
Hi, first of all, thank you so much for bringing us this helpful and amazing plugin!

However, I just found it doesn't work very well while using the plugin [maximise active pane](https://github.com/deathau/maximise-active-pane-obsidian). 

To be more specific, when a pane is maximised to occupy all the space, and the hover editor is triggered somehow (for example, there's an internal link inside of the maximised pane, or by using some other plugins like [markdown table editor](https://github.com/ganesshkumar/obsidian-table-editor) that can invoke a hover editor), we get some unexpected behavior.

In this case, the hover editor pops up fine, but after a short flicker, in the background, the maximised pane below the hover window, becomes blank. Is it possible to fix this? Thank you in advance. I really appreciate your work.

**Comment by pjeby** [comment]
This has to be fixed in the other plugin; see https://github.com/deathau/maximise-active-pane-obsidian/issues/17

(A similar problem applies to using maximize active pane with Obsidian 0.15.3, which can have active panes in sidebars and popout windows, and requires a similar fix, so it's possible it'll be fixed at the same time.)
