### ISSUE TITLE
Automatically (but temporarily) reveal hovered link/file

### ISSUE THREAD

**Issue by nickchomey** [nothingislost/obsidian-hover-editor#148]
I love the Auto Focus feature of this plugin for identifying where the hovered link/file is in the folder hierachy, but I have one suggestion to make it better.

When you hover a link whose file is within a collapsed folder, the folder/file does not get focused. The folder needs to be expanded in order to show the Focus.

This plugin automatically reveals any active file, but it quickly makes the folder sidebar very messy as all folders remain expanded.
https://github.com/shichongrui/obsidian-reveal-active-file

My suggestion to enable hovering a link to expand the folder structure to show the file, but then collapse it to the pre-hover state when the hover ends. 

That plugin doesn't really have any hover/temporary characteristic so it doesn't make sense to add this funcitonality to it. So, I presume that you could either integrate with that plugin in some way or, better yet, just borrow its code and implement a modified version within your plugin as it seems better to have all the code in one plugin.

Here's a screen recording to show how it works with both plugins enabled.

https://user-images.githubusercontent.com/88559987/174646207-0371437e-b790-4e42-9e06-5beb176709b9.mp4

Please let me know if anything isn't clear.

Thanks!

**Comment by pjeby** [comment]
Have you considered using a plugin like Quick Explorer or Show Path in Status Bar (in place of Reveal Active File)?  These plugins would let you see the path of the active file at all times, including hover auto-focus, but do not disrupt the state of the file explorer.  You could then use the hotkey to reveal the active file only when you actually want to look at that folder (vs just seeing the path).

**Comment by pjeby** [comment]
When you hover a link with Hover Editor and have auto-focus on, Quick Explorer will change the title bar to show the path of the hovered link.  If you then hit the hotkey for QE's "browse current folder" command you will be browsing the link's folder (and the hierarchy above it), without affecting your file explorer pane. 

Does that work for what you're trying to accomplish?

**Comment by pjeby** [comment]
I think I'm still confused as to what it is you're looking to do.  I initially assumed the question was, "How can I see the full path for the link I'm hovering?", which is answered by the path-in-status-bar and quick-explorer plugins because if you autofocus the hover editors you'll see the path in a designated area.

But it sounds like you want something like, "See the other files in the same folder as the link I'm hovering"?  Is that correct, or am I still misunderstanding?

**Comment by pjeby** [comment]
(Also, the Escape key closes quick explorer so you don't need to click away in that scenario.)

**Comment by pjeby** [comment]
At the moment, it sounds like the problem would be best resolved by asking the creator of the Reveal Active File plugin to implement restoring the explorer's state when you navigate away from a file.  This would then work fine with Hover Editor as it stands, since when the hover editor closes the focus will return to an existing pane.

So if RAF keeps track of the folders it opens when revealing a file, it can close them whenever it reveals a new file.  This would address your use case *and* make the RAF plugin more generally usable even in the absence of Hover Explorer.  (I once tried RAF a very long time ago and found the opening of all the folders quite annoying, and eventually ended up creating Quick Explorer as an alternative to that and/or trying to make the File Explorer only ever show one folder at a time.)

**Comment by pjeby** [comment]
By the way, there is also a [Collapse All](https://obsidian.md/plugins?id=obsidian-collapse-all-plugin) plugin that collapses all the folders in the explorer, and has a command you can assign a hotkey to.  You might be able to ask that plugin's developer to add a feature to automatically collapse anything that isn't the current file, or the RAF developer to have an option to issue the collapse-all command before issuing the show-in-explorer command.  (And of course, you could use the hotkey as a partial workaround in the meantime.)

I'm going to close this issue now since managing the file explorer is really outside the scope of what Hover Editor does, but I hope you find what you're looking for.
