### ISSUE TITLE
For the note page displayed in a separate window (through the "move to new window" command), if the link contained in it is opened with hover editor, the shortcut key of "ctrl+F" cannot be used in the floating page

### ISSUE THREAD

**Issue by Xieleilab** [nothingislost/obsidian-hover-editor#162]
For the note page displayed in a separate window (through the "move to new window" command), if the link contained in it is opened with hover editor, the shortcut key of "ctrl+F" cannot be used in the floating page

**Comment by pjeby** [comment]
I'm not able to reproduce this problem.  Can you give more specific steps?  Is the hover editor in editing mode or reading mode?  Which versions of the plugin and Obsidian are you using?  Are you using Sliding Panes, Pane Relief, or any other pane-management plugins?

**Comment by Xieleilab** [comment]
ADJUSTED STATEMNET:
in obsidian V0.15.6, For the note page displayed in a separate window (through the "move to new window" command),if the link contained in it is opened with hover editor(V0.11.3) in editing mode, the shortcut key of "ctrl+F" cannot be used, besides, Sliding Panes is not installed, the version of plugin "Pane Relief," is  0.2.4

**Comment by pjeby** [comment]
I still can't reproduce this.  I am

1. Opening a new pane in edit mode
2. Moving that pane to a new window, either with the keyboard command or the menu item
3. Hover a link in that note in the new window, creating a hover editor (which is auto-focused)
4. Ctrl-F brings up the search dialog

Is your hover editor focused in step 3?  Do you have the pane header visible?  Do other keyboard commands work in the hover editor?  What happens if you click in it?

**Comment by Xieleilab** [comment]
thanks a lot ! it now works when i update the plugin pane relief!
