### ISSUE TITLE
Has Hover Editor become abandonware?

### ISSUE THREAD

**Issue by DutchPete** [nothingislost/obsidian-hover-editor#172]
There have not been any replies to issues for over a month: is this plug-in still actively maintained?

**Comment by pjeby** [comment]
The best way to tell this about a project is not to check how long issues have been open, but how recently issues have been *closed*.

**Comment by DutchPete** [comment]
I don't quite agree with that statement. If someone opens an issue I would expect the dev to reply sometime along the line, even if it is only to say “this is low priority for me”, or whatever else.

Still, looking at the issues recently closed, most of those were done by you. That brings me back to my previous question: have you taken over from @nothingislost?

So, if the Hover Editor plug-in is not abandonware, then are you just answering people's questions, or have you taken over the plug-in?

May we please know what the status is? And if you don't know, please say so.

**Comment by pjeby** [comment]
Your original question was, "is the project actively maintained?"  The answer is *yes*, as you can see by both the closed issues and the recent commits (visible on the main project page).

> If someone opens an issue I would expect the dev to reply sometime along the line, even if it is only to say “this is low priority for me”, or whatever else.

And for many open source projects "sometime along the line" can be months or years.  A polite way to handle this is to provide additional information on the *specific* issue in question, or inquire (again, in *that* issue) whether any additional info is needed or there is anything else you can do to help move the issue along.  Opening additional issues, using inflammatory language ("abandonware"), and demanding potentially-private information about the people behind a project, however, can come across as rude and entitled, and creates more work for the project maintainers, which they will *not* be happy about.

All I will say about the status of current work on the project is:

- I am continuing to work on improving 0.16 compatibility, and have a list of specific things I intend to tackle on that as time permits.  Priority will be given to functional issues, such as the docking problem.
- Some of the plugin's future direction (e.g. how to deal with tabs and splits) and specific issues (such as those related to move/resize) will require input from @nothingislost in order to move forward
- I am not currently commenting on or closing issues that are not in my area of expertise and/or require said input to resolve

If you have any specific questions about my plans with regard to various aspects of the *plugin*, I will certainly attempt to answer them.  But I won't be answering any questions regarding the *people* working on the project.

**Comment by nothingislost** [comment]
Appreciate you jumping in @pjeby. I am still maintaining this plugin but haven't had cycles to look at it much over the past month due to other commitments. @DutchPete have some patience and please be polite to the maintainers of this plugin which was written during our free time for the benefit of the community.

**Comment by DutchPete** [comment]
@nothingislost I have no problem exercising patience, esp. since it is a free plug-in, I am in no position to demand anything. It is one heck of a fine plug-in.

Having said that, I do not believe I was rude to @pjeby. I noticed he answered issues even though it is not his plug-in originally. When I had an issue that he answered and closed immediately without checking if it worked, I was surprised, esp. since his solution did not work at first. So, I asked to reopen it and also tried to understand what his role was and what the status of the plug-in was.

I felt he was not clear in answering the latter issue, so I pushed him a bit on that. When he cleared it up I stopped pushing. He also help me solve the original issue I had, and was grateful for it.

I honestly do not believe that signalling me issue was not solved or pushing someone to be clear about a status equates to being impolite. I have never lacked respect to you whenever we communicated directly on Discord, so you know it is not my way.
