### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by DutchPete** [nothingislost/obsidian-hover-editor#174]
Thanks for your detailed answer, I understand a bit better now. I am still surprised a plug-in by @nothingislost suddenly seems to have moved over to someone else. Never mind.

In any case, my issue #171 has NOT been resolved. You provided an answer that had nothing to do with the issue, as I explained after you closed it. So, please tell me, is my issue solvable or not? If not, you can keep it closed. If it is solvable, please reopen it.
Thank you.

P.S. Regarding not opening duplicate issues, I concur that I should not do that, in principel. However, if you close an issue before asking whether your proposed solution works, then you are in effect forcing me to open a duplicate if your solution did not work.

**Comment by pjeby** [comment]
> you are in effect forcing me to open a duplicate if your solution did not work

As far as I'm aware, nothing stops you from replying to closed issues.  From the developer side, closing an issue simply means "As far as I know, I don't need to follow up on this any more, because if there's still a problem the other person can write back."  If we're wrong, we simply reopen at that point.

> I am still surprised a plug-in by @nothingislost suddenly seems to have moved over to someone else

That's understandable, since **no such move has taken place**.  This project has multiple contributors and committers, as can be seen on its front page.  (My name is on many of the releases from even before I was an official contributor.)  Sometimes I am more active, sometimes others are.  Sometimes we are all relatively inactive at once.  That is simply normal life in volunteer-run open source development.

Please stop opening duplicate issues.  You can reply to closed ones just fine, and if there is something that needs doing *other than* sending you a reply, I will re-open them.  Open issues are for things requiring investigation or action our part, or where we wish to remember to follow-up with someone.  If there is no next action on our side for us to *do*, there is no reason to keep it on our figurative to-do list.

In the case of #171, for example, it sounded like a straightforward case because lots of people have been asking about the view/edit icon on the Inisder Build discord channel, and Hover Editor does not create or control that icon -- so from my POV the question was unlikely to require any follow-up, except perhaps for clarifying questions which I would address by replying to my notifications.  (Devs receive notifications even for replies to closed issues, so closing the issue does not mean we won't reply, just that we're clearing our main, shared to-do list of things we don't expect to need further action.)
