### ISSUE TITLE
[Feature Request] Hotkey to open daily note in hover editor

### ISSUE THREAD

**Issue by b0o** [nothingislost/obsidian-hover-editor#175]
I like to refer to my daily note regularly throughout my day, but I don't necessarily want to always keep it open in a pane. It would be very useful to be able to quickly open my daily note in a hover editor window using a hotkey.

**Comment by pjeby** [comment]
You might want to try the QuickAdd plugin for this, as it lets you combine Obsidian commands (like "open hover editor" and "open daily note") into a single "macro" command that you can then assign a hotkey to.  It's not terribly easy to configure, but the result is easy to use.

The basic procedure is you go into QuickAdd's settings, click Manage Macros, enter a name and click Add Macro.  You then click "Configure" on the macro and add the commands you want the macro to run.  (e.g. "Open new hover editor" and "Open today's daily note").  Between them, you'll want to add a delay (click the clock-face icon) of at least 300-400 ms (click where it shows 100 and edit it.) Then, you leave that area and the macro manager to go back to its settings page.

Then, this is the weird bit - you have to now add a "Choice".  Type a name for the command in the text box, then pick "Macro" from the dropdown, and "Add Choice".  (The name you type in will be the name of your new command in the Obsidian command list, so you might use something like "Open daily note in hover editor".)

Next to your newly added "choice" there will be a lightning bolt and a gear.  Click the gear *first*, and pick the macro you created from the dropdown, then exit that dialog and click the lightning bolt.  It will turn yellow to show your command is enabled.

Now, if you go to the hotkeys or command palette, you'll see a new "QuickAdd: Open daily note in hover editor" command.  If you need to change how it works or change any settings for it in the QuickAdd settings, you'll need to click the lightning bolt twice after making changes - the first click removes the command, the second adds it back with the new settings.

Anyway, it's not perfect but it can be made to work as long as you have enough of a delay set between the two commands (otherwise the daily note will open in your current pane or tab and the hover editor will be empty).

Alternately, if you prefer not to do all that, you might want to just assign one hotkey to "open new hover editor" and another to "open today's daily note" that you can easily hit as a combo (e.g. two letters with the same modifier keys).

**Comment by b0o** [comment]
Wow, that works perfectly! Thank you very much for the detailed explanation.
