### ISSUE TITLE
Extra white space on embeds in second window open tab, on Obsidian start

### ISSUE THREAD

**Issue by enteleos** [nothingislost/obsidian-hover-editor#210]
Embeds inside a note display strangely when a) that note is open in a second window, and b) Obsidian is started or the vault is opened. The strangeness: Vast white space under the contents of the embed, added as if it is a part of the embed. Clicking the embed line clears the white space.

**Comment by enteleos** [comment]
This:
![image](https://user-images.githubusercontent.com/95007633/229842771-4f91cf86-d807-48ed-93d8-70f0105ea5a8.png)
Turns into this when closing then restarting Obsidian:
![image](https://user-images.githubusercontent.com/95007633/229843274-d69aefb3-ac1a-4d16-9819-790649e7f745.png)

**Comment by pjeby** [comment]
Sorry, how does this relate to Hover Editor?  Those pictures look to be of
the regular Obsidian editor.  (It also looks like maybe an issue related to
your theme or a CSS snippet - have you tried using the sandbox vault?)

**Comment by enteleos** [comment]
So sorry, should have made it clear. I have four plugins running: Novel Word Count, Smart Typography, TimeStamper, and Hover Editor. Turning off only Hover Editor makes the behavior stop. Also, this is on the insider build, I'm pretty sure starting with 1.2.0, but I didn't investigate fully until today on 1.2.2.

**Comment by pjeby** [comment]
If you can identify the CSS involved that would be helpful; the part where it only happens when you restart Obsidian really makes it sound unrelated to Hover Editor.  Can you reproduce the issue with the other plugins disabled, but Hover Editor enabled?

Also, your pictures show different things at the top of the display - one shows a title bar and the other does not.  Is that just an artifact of how you took the pictures or is that part genuinely different?

**Comment by enteleos** [comment]
Whew, after turning plugins on and off, testing this and testing that, I have to say it's just kinda funky. I'm having trouble getting consistent behavior. When I turned off all but Hover Editor, it stopped happening, but when I turned all four back on, the behavior did not come back. Can't even get it to happen again at the moment, no matter what I do, so can't report on CSS. I'll keep an eye on it over coming days and see if I can figure out how to narrow it down, whether Hover Editor is involved or not, and come back with an update if something new shows up to clarify things.

The pictures showing differently at the top has to do just with what I grabbed with my screen capture app, not genuinely different.

**Comment by pjeby** [comment]
That makes it sound like it could be an ordering issue with plugins' CSS -- when you turn plugins on and off, it changes what order they load in, such that newly turned-on ones will now load after all the ones that were already on.

If it's a CSS order dependency between HE and the other plugins, then turning HE off, the others on, then HE on again might get it back to the order where it breaks.  But it could also just be an order issue between the other three plugins, so you might try turning them all off, and then turn them on in different orders to see if it reproduces.

It seems really unlikely to be HE-related though, since HE doesn't style anything to do with previews or embeds that aren't *inside* a hover editor.

Just to be clear - the affected notes are not being put into a hover editor and then turned back into a tab or anything like that?  They're just plain ol' regular Obsidian note tabs?

**Comment by enteleos** [comment]
Yes, the notes are just plain ol' regular Obsidian note tabs.

After shutting down for the night, firing up Obsidian this morning gave the issue once again. (Why only after shutting down? I'm on Windows 10 in case that's relevant.)

Anyway, after futzing around a while, I finally turned off all plugins including HE, and the issue persists. Will take it back to Discord to see what they can make of it.

Thanks for your help, and sorry for jumping to conclusions based on a limited test.
