### ISSUE TITLE
[BUG] Tasks Plugin's Baclinks causing scroll on note

### ISSUE THREAD

**Issue by ertugruluyar-github** [nothingislost/obsidian-hover-editor#211]
This bug only happening on reading view.
https://user-images.githubusercontent.com/70096810/229996091-44a9ac1e-d8ee-48f3-b94d-fb455915010a.mp4

**Comment by pjeby** [comment]
Can you reproduce this in a sandbox vault with the stock theme and no plugins besides Hover Editor?  Also please indicate your Obsidian version.  Thanks.

**Comment by ertugruluyar-github** [comment]
Ek olarak, obsidiyeni ilk açtığımda herhangi bir hata yok, ancak dosyayı kaydırıp bağlantının üzerine geldiğimde hata oluşmaya başlıyor.

**Comment by pjeby** [comment]
Google translated your message as: "Additionally, when I first open obsidian there is no error, but when I scroll the file and hover over the link, the error starts to occur," but that doesn't answer any of the questions I asked.

**Comment by pjeby** [comment]
Does it happen without the Tasks plugin active, though?

**Comment by ertugruluyar-github** [comment]
When I disabled the Hover editor, bug disappear. 
I can't disable the Tasks plugin because this task list came from Tasks plugin.

**Comment by pjeby** [comment]
Quick question: do you have automatic focus turned on for Hover Editor?  That is, is focus going to the hover editor when it pops up?

**Comment by ertugruluyar-github** [comment]
In my vault, I tried the disable auto focus, but the bug still happened.
In sandbox vault, I disabled the auto focus then restart the app, first its work when I didn't scroll the note yet. When I scroll and tried the hover on, bug was happening.
Then tried "auto pin = always" settings and bug still remaining.
Then tried "default mode = editing view" settings and bug still remaining.
Then tried "default mode = match current view" settings and bug still remaining.

But when I changed the note view mode to editing view from reading view, bug is gone.
![Screenshot_2023-04-07_11-06-41_x](https://user-images.githubusercontent.com/70096810/230569809-6dc6dcd3-04e9-422a-961b-2e676d5f3fba.gif)

**Comment by ertugruluyar-github** [comment]
Its could be the Tasks plugin bug I think. ?

**Comment by pjeby** [comment]
When a hover editor pops up, a couple of Obsidian events are triggered, to tell plugins that the workspace layout has changed (because there's a new pane open) and that a file has opened.  These events can't be disabled, because then lots of other features and plugins would not work correctly.  If the Tasks plugin (or something else) is responding to these events by re-rendering the pane that was hovered, then yes, it certainly could be Tasks that is responsible.

A quick search of the Tasks plugin's code does not show any obvious way in which they are responding to those events, though.  But it could be indirect.

In any case, there is nothing that Hover Editor does to directly affect the thing(s) you hover over.  But since it does create a new pane and open a file to show in that pane, it does trigger Obsidian events that tell *all* plugins that the workspace layout has changed and a file has been opened.  Any plugin, or Obsidian itself, could then do pretty much anything in response that could trigger a re-rendering of the reading view, and identifying which plugin it is would be difficult.

All I can suggest is putting similar links in a similar note, but *not* using Tasks -- if the issue still happens then it is an issue with Obsidian core, otherwise it is most likely an issue with Tasks.

**Comment by ertugruluyar-github** [comment]
Thank you for everything.

**Comment by ertugruluyar-github** [comment]
I tried the new update (version 0.11.12) and the issue solved.

**Comment by pjeby** [comment]
Yeah, it's an [issue with Obsidian](https://forum.obsidian.md/t/preview-mode-scrolls-by-itself-when-other-panes-change/61311) that was doing this, that I added a workaround for in 0.11.12.  (See issue #222 for more details.)
