### ISSUE TITLE
The Page Preview plugin auto-scrolls before I can click any indented link in Reading Mode

### ISSUE THREAD

**Issue by Maskscot** [nothingislost/obsidian-hover-editor#222]
Hey there, I need help with clicking indented links on my bullet points, but the Page Preview plugin in reading mode keeps scrolling down before I can click on anything. None of my other plugins are interfering btw. I want to cease the scrolling when I use Page Preview before clicking on links.

To recreate this, simply make a bullet point, and then add several indented bullet points with links under the initial bullet point.

https://github.com/nothingislost/obsidian-hover-editor/assets/112918049/0057aaac-b12b-41e0-8068-8eb5941d7123

**Comment by pjeby** [comment]
Can you reproduce this in a fresh sandbox without the stock theme, no other plugins, and no CSS snippets?  If so please post or upload the text in question so I can attempt to reproduce it.

**Comment by Maskscot** [comment]
Sure! Here I'm trying to click on the first indented link, but it keeps cutting down. Here's also a link to the sandbox.

https://github.com/nothingislost/obsidian-hover-editor/assets/112918049/3725ea09-9257-4be2-b9ec-93d7e5f007d4

[Test.zip](https://github.com/nothingislost/obsidian-hover-editor/files/11699656/Test.zip)

**Comment by pjeby** [comment]
Ok, so this issue is actually an Obsidian issue - I can get it to happen (jump-scrolling) without Hover Editor by explicitly requesting a workspace re-layout in the dev console, or by splitting right.  It's tricky as it doesn't happen literally every time; it's a lot easier to trigger the scroll with hover editor on.  The nested list isn't the key part either - I can make it happen with any list as long as a list has been scrolled partway off-screen.

I will talk to the Obsidian devs and see if they have any ideas on how to prevent this.

**Comment by pjeby** [comment]
While I'm waiting to hear back from the Obsidian devs, I have released Hover Editor 0.11.12 with a workaround for this issue, and confirmed the fix in my local copy of your demo vault.  Please let me know if it fixes the issue in your real vault as well.

**Comment by Maskscot** [comment]
Splendid! The new update fixed my problem, for now I can click and stop anywhere I please. 

https://github.com/nothingislost/obsidian-hover-editor/assets/112918049/24cab107-e886-4bdf-ab60-145c7f11412d

Thank you very much for helping me here!
