### ISSUE TITLE
No space between line numbers and content in live preview mode using Minimal theme

### ISSUE THREAD

**Issue by waltcf** [nothingislost/obsidian-hover-editor#226]
I just installed Hover Editor, which strikes me as a very clever and awesome plugin! However, with the Minimal theme active and line numbers on, there is no space between the numbers and the note content when the hover editor is switched to editing mode. (I checked in a sandbox vault, and the default Obsidian theme + line numbers looks fine.)

I don't know if that's a supportable issue or not, but since Minimal is a pretty popular theme, I figured it was worth bringing up. 

Here's a screenshot of what I mean:

![image](https://github.com/nothingislost/obsidian-hover-editor/assets/90991600/108f7979-dc1f-42ed-8c29-a9a607e06dda)

**Comment by pjeby** [comment]
We can't really change the plugin to support specific themes; it's generally themes that have to be changed to support plugins, as Obsidian doesn't provide a way for plugins to scope CSS changes for specific themes.  (That is, there's no way for a plugin to say in its CSS, "apply this bit if theme X is the active theme".)

Anyway, you need to take this issue to the theme developer, since we can't really do anything about it here.
