### ISSUE TITLE
FR: Create new files when hovering over links to documents that do not exist

### ISSUE THREAD

**Issue by HEmile** [nothingislost/obsidian-hover-editor#4]
I wasn't sure about it when I heard of all these ideas of hover editors, but now that I'm using it I can already see how this will speed up my workflow significantly, thank you so much! Truly a gamechanger :)

Here is one FR: The hover editor does not work when hovering over links to non-existing notes. It would be very useful if the plugin were to create an empty file when hovering over it. I _very_ frequently create links to nonexisting notes and just add some metadata there, not having to navigate to that page would be super helpful for me.

**Comment by nothingislost** [comment]
Yeah, agreed. I will be addressing that in a future release. For now, it default back to the native Page preview behavior for certain things such as hovering over a link that does not exist.

Same goes for quick explorer. Previews invoked via quick explorer will default back to the native preview since I have some more work to do to make this play nicely with the quick explorer implementation.

**Comment by nothingislost** [comment]
This is now part of 0.3.3. It's pretty basic right now but let me know how it goes.

**Comment by HEmile** [comment]
Thanks! It seems to give a clickable button when hovering. When using the keyboard to open the hover, it doesn't seem to work though. (Ideally it'd create it and not show the button when using the keyboard, but that's my opinion. Also, I'd love not to have to use the mouse here, I very frequently create files).

**Comment by nothingislost** [comment]
[v0.3.6](https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.3.6) should get you the behavior you're looking for.
