### ISSUE TITLE
Add compatibility for Hider when App Ribbon is hidden

### ISSUE THREAD

**Issue by kepano** [nothingislost/obsidian-hover-editor#71]
When using the Hider plugin with App Ribbon hidden the "snap to viewport" mode should not have a 30px gap on the left side, and instead fill the screen.

**Comment by nothingislost** [comment]
It only does that if you're using Minimal theme ;)

I actually calculate that value dynamically based on `document.body.querySelector(".mod-left.workspace-ribbon").offsetWidth` since different themes change the width of that element. Minimal puts in down in the bottom right and keeps 30px visible as a moueover trigger.

I think I may be able to handle this by adding another check to see how tall the ribbon is... or maybe if the `hider-ribbon` is present... we'll see.

**Comment by kepano** [comment]
Interesting, sometimes it doesn't seem to detect correctly and leaves a gap in Minimal. I haven't figured out the exact conditions yet.

**Comment by nothingislost** [comment]
Yeah, that's what I'm saying. Minimal keeps the ribbon width at 30px even when using hider to hide it. It just becomes transparent :)

**Comment by kepano** [comment]
Ah yes... You might want to also test California Coast too. I think any theme that has the ribbon moved to the bottom left corner on hover will have that issue because you need the ribbon element to have width in order to make it available on hover.

**Comment by nothingislost** [comment]
This was resolved in https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.7.0
