### ISSUE TITLE
Excalidraw + auto-focus + (Quick Explorer or Pane Relief) = lost keyboard control

### ISSUE THREAD

**Issue by pjeby** [nothingislost/obsidian-hover-editor#85]
Hovering an Excalidraw drawing from a QE or PR menu seizes focus and prevents keystrokes from reaching the menu.  I'm not sure if this is something that *can* be fixed in HE or whether it needs to be fixed in Excalidraw or my plugins, but putting this as a placeholder here in case you have any ideas first.  ;-)

**Comment by nothingislost** [comment]
Looks like it's due to Excalidraw taking over the keybinding scope https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/7a2509911bbcc47c1c418c51d57c6ec4cbe86912/src/main.ts#L1511

Looks like I'm partially to blame https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/300 for this approach ;)

I think the best solution would be to see if we can solve the ctrl+enter problem in that issue without completely overriding scope.

**Comment by pjeby** [comment]
Ok, here's how: instead of creating a new scope and pushing it, do this:

```ts
declare module "obsidian" {
    // Add these to top of file
    interface Keymap { getRootScope(): Scope }
    interface Scope { keys: any[]; }
}

// === code below replaces block at line 1511 === //
const scope = app.keymap.getRootScope();
const handler = scope.register(["Mod"], "Enter", () => true);
scope.keys.unshift(scope.keys.pop());  // Force our handler to the front of the list
self.popScope = () => scope.unregister(handler);
```

This should put the key handler in at a lower precedence than menus or modals' scopes, but still higher precedence than Obsidian command hotkeys.

**Comment by nothingislost** [comment]
Ah, smart. You going to open a PR/Issue for that on the Excalidraw repo?

**Comment by pjeby** [comment]
Yep.  Just sent in the PR.
