### ISSUE TITLE
Decouple hover editors from the native HoverPopover class

### ISSUE THREAD

**Issue by nothingislost** [nothingislost/obsidian-hover-editor#96]
Subclassing the native HoverPopover class is getting too complicated and brittle. For long term stability, it would probably be best to completely decouple the HoverEditor implementation from any native HoverPopover dependencies.

A good example of the hidden complexity is found in the native HoverPopover detection and reaping logic. Natively, Obsidian has logic to ensure that only a single HoverPopover is open at any given time. That single popover can spawn additional child popovers but there can only ever be one popover per parent.

As such, the native logic has the following internal code for detection and reaping. We're currently coexisting with this logic but in most cases, this logic is problematic and unnecessary. For example, whenever a popover is open, there's an interval that goes off every 500ms that tries to close popovers. There's also a mousemove listener constantly refreshing the `mouseCoords` object. So, if you have pinned popovers, this logic is sitting there wasting cycles for no benefit.

We currently do a lot of work to coexist with this internal logic that could be removed if we stopped subclassing. Methods like `explicitHide()` exist because the reaping logic is constantly calling `hide()` on our persistent popovers.

The variable/function naming below is defined by me since this code is typically minified and has variable names like `kI` and `mI`

These are all defined at the root of the internal app scope

```js
var initializingHoverPopovers = [];
var activeHoverPopovers = [];

var popoverCheckerInterval = 0;
var mouseCoords = null;

var closeAllPopovers = function () {
    for (var e = 0, t = initializingHoverPopovers; e < t.length; e++) {
        t[e].hide();
    }

    setTimeout(function () {
        for (var e = 0, t = activeHoverPopovers; e < t.length; e++) {
            t[e].hide();
        }
    }, 5);
};

var closeInitializingPopovers = function () {
    for (var e = 0, t = initializingHoverPopovers; e < t.length; e++) {
        t[e].hide();
    }
};

var setMouseCoords = function (e) {
    mouseCoords = {
        x: e.clientX,
        y: e.clientY
    };
};

var popoverChecker = function () {
    if (mouseCoords) {
        if (0 === activeHoverPopovers.length) {
            document.removeEventListener("click", closeAllPopovers);
            document.removeEventListener("contextmenu", closeInitializingPopovers);
            document.removeEventListener("mousemove", setMouseCoords);
            clearInterval(popoverCheckerInterval);
            popoverCheckerInterval = 0;
        } else {
            for (var e = document.elementFromPoint(mouseCoords.x, mouseCoords.y), t = 0, n = activeHoverPopovers; t < n.length; t++) {
                n[t].detect(e);
            }

            for (var i = 0, r = activeHoverPopovers; i < r.length; i++) {
                r[i].transition();
            }
        }
    }
};

// this is called by the HoverPopover constructor and also HoverPopover.show()
var initializePopoverChecker = function () {
    if (!popoverCheckerInterval) {
        document.addEventListener("click", closeAllPopovers);
        document.addEventListener("contextmenu", closeAllPopovers);
        document.addEventListener("mousemove", setMouseCoords);
        popoverCheckerInterval = window.setInterval(popoverChecker, 500);
    }
};
```

cc: @pjeby for thoughts

**Comment by pjeby** [comment]
Yeah, at this point we are definitely doing a lot of work to work around the base class, so I don't mind it changing, *provided* that we keep enough of the interface compatible with the old implementation that it's easy for plugins that manipulate popovers to treat them similarly.  (E.g. QE's positioning, closing, etc.) But yes, the above code is almost completely useless to us.

It occurred to me the other day that we could fix the stuttering popups problem (both for the Calendar and for live preview defocusing) by tracking the mouse position in order to know if the new event occurred at the same mouse position and link text as the existing popup, even if the target element changes.  In such a case we could change the target element of the popover and tell it to transition(), which would then do nothing since the mouse is on the replaced element.  This would allow us to get rid of the Calendar-specific logic for setActiveLeaf, and would fix the problem generically for any view that rerenders when the active leaf is changed.

(I mostly mention it here in part because the global tracking of the mouse position is something we don't have direct access to and thus might end up duplicating anyway, in order to know if the mouse had actually moved.  (Though saving the target's rectangle and seeing if the new target rectangle overlapped would actually suffice for this purpose, so long as the link text and other parameters matched those used to invoke the current popup.))

Hm.  One problem I see, though, is that if we *don't* inherit from HoverPopover, then code doing instanceof checks will fail.  But that can be worked around with some prototype hacking, I suppose.

I guess all in all what I'm saying is that I think we need to document a common API subset for the core hover popover that HE's will also stick to, so there can be interop.  (Some of that is also needed to ensure HE's stays compatible with what the core does to hover popovers as well.)
